export const datosExtra = [
    { "idproducto": 301,
      "detalle": "Bloquean el 99% de los rayos UVA y UVB.Cuentan con una pantalla 90% de luz visible y coinciden perfectamente en color y no presentan distorsiones e imperfecciones. Ideal para vos!!!",
      "especificaciones": "Anteojo de sol Gaal 1004 ngm g15 Color del cristal Negro Estilo Rectangular Genero Unisex Color Negro",
      "imagen": "lente de sol.jpg",
    },
    { "idproducto": 302,
      "detalle": "Diseñadas para reducir y filtrar la cantidad de rayos de luz azul que llega al ojo y ayudan a evitar que causen daños potenciales. Reducen la fatiga ocular y mejoran el contraste.",
      "especificaciones": "Anteojo Blue Filter Gaal 2004 tr bt40 Color del cristal Transparente Estilo Redondo Genero Unisex Color Dorado opaco",
      "imagen": "lentes bluefilter.jpg",
    },
    { "idproducto": 303,
      "detalle": "Proporcionan una buena visibilidad a través del agua, son tu mejor elección si nadas por ocio y para mantenerte en forma, especialmente si no tienes costumbre de usar Gafas de Natación. ",
      "especificaciones": "Gafa sport Gaal 5000 tr kl80 Color de cristal Transparente y Resistente",
      "imagen": "gafas natacion.jpg",
    },
    { "idproducto": 304,
      "detalle": "La exclusiva marca Betania llega con esta colección de anteojos recetados hechos en Orgánico/Plástico que cuenta con un diseño cómodo y moderno, ideal para usar con tu receta de anteojos. Al ofrecer protección UV400, las gafas bloquean casi toda la exposición a los rayos UVA y UVB. Esto no sólo protege su visión, sino que también protege la piel alrededor de los ojos del sol. Corrigen los problemas de visión y le devuelven una visión nítida. (No son lentes polarizadas).",
      "especificaciones": "Marca Betania Modelo 8837C1 Unisex Material Vidrio Orgánico Armazón Plástico Forma Rectangular",
      "imagen": "lentes de lejos.jpg",
    },
    { "idproducto": 305,
      "detalle": "La exclusiva marca Betania llega con esta colección de anteojos recetados hechos en METAL-ACETATO que cuenta con un diseño cómodo y moderno, ideal para usar con tu receta de anteojos. Este diseño brinda confort y sirve para lucir siempre sofisticado/a. Su estilo particular se ajusta a tu rostro brindándote una apariencia renovada y única, como solo Betania puede darte.",
      "especificaciones": "Marca Betania Modelo 8837C13 Unisex Material Vidrio Acetato Armazón Metálico Forma Rectangular",
      "imagen": "lentes de cerca.jpg",
    },
    { "idproducto": 306,
      "detalle": "Anteojo Marca Betania, estos armazones están realizados con un material noble, hipoalergénico e irrompible, y por su diseño ergonométrico se adaptan totalmente a la fisonomía del rostro. Colores Varios",
      "especificaciones": "Marca Betania Modelo 845C3 Para Niños Unisex Material Vidrio Acetato Armazón Plástico Hipoalergénico Forma Rectangular",
      "imagen": "lentes de niño.jpg",
    },
    { "idproducto": 307,
      "detalle": "Las lentes multifocales o también llamadas progresivas tienen más de una graduación y corrigen la vista en todas las distancias, para que no tengas que estar cambiando de anteojos. Son comúnmente utilizadas por personas que tienen Presbicia. Alrededor de los 40 años es normal que te cueste ver bien de cerca, por ejemplo si estas haciendo zoom para leer mejor desde tu celular o estirando el brazo para ver con nitidez es probable que estes comenzando con la Presbicia.",

      "especificaciones": "Marca Estilo Retro Vintage Modelo Multifocales en Policarbonato Unisex Material Metal Forma Cuadrada",
      "imagen": "lentes multifocal.jpg",
    },
    { "idproducto": 308,
      "detalle": "Estas gafas cuentan con filtro polarizado. Reducen sensiblemente el reflejo en superficies como pavimento, autos, agua o nieve. Por lo tanto, son muy recomendables para practicar deportes (running, ciclismo, pesca, golf) o para conducir en la ruta. Reducen la fatiga visual y son muy recomendables para personas con alta sensibilidad a la luz o fotofobia.",
      "especificaciones": "Marca Go Modelo PLK Certificación: CE - Estampillado Marco: TR90 Material lentes: Policarbonato Proteccion: UV400 (protección UV-A y UV-B) Peso: 30grs aprox.",
      "imagen": "gafas deportivas.jpg",
    },
    { "idproducto": 309,
      "detalle": "Las gafas de seguridad son equipos de protección individual que sirven para proteger los ojos y la parte circundante en determinadas situaciones de riesgo. Es obligatorio usar gafas de seguridad cuando existe riesgo de que se proyecten objetos o líquidos que pueden provocar daños a la vista. Nuestros Modelos cuentan con Tecnología patentada de difusión de presión en las patillas, que permite que el lente se autoajuste a varios tipos de caras humanas. El recubrimiento anti-empañante Scotchgard™ dura más que cualquier recubrimiento anti-empañante tradicional, ayudando a mejorar el desempeño de los lentes en ambientes húmedos y con vapor.",
      "especificaciones": "Marca 3M Modelo SecureFit 37510 AS OTG TRANSPARENTE Material:Policarbonato  Tipo de protección:Frontal  Tipo de tratamiento del cristal:ANTIRAYAS",
      "imagen": "gafas de proteccion.jpg",
    },
    { "idproducto": 310,
      "detalle": "Los lentes de tendencia son equipos de protección individual que sirven para proteger los ojos y la parte circundante en determinadas situaciones de riesgo. Es obligatorio usar gafas de seguridad cuando existe riesgo de que se proyecten objetos o líquidos que pueden provocar daños a la vista. Nuestros Modelos cuentan con Tecnología patentada de difusión de presión en las patillas, que permite que el lente se autoajuste a varios tipos de caras humanas. El recubrimiento anti-empañante Scotchgard™ dura más que cualquier recubrimiento anti-empañante tradicional, ayudando a mejorar el desempeño de los lentes en ambientes húmedos y con vapor.",
      "especificaciones": "Marca 3M Modelo SecureFit 37510 AS OTG TRANSPARENTE Material:Policarbonato  Tipo de protección:Frontal  Tipo de tratamiento del cristal:ANTIRAYAS",
      "imagen": "gafas deportivas.jpg",
    },
]
