# Generated by Django 4.2 on 2023-05-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('idabono', models.IntegerField(db_column='idAbono', primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'abono',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idciudad', models.IntegerField(db_column='idCiudad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.IntegerField(db_column='idCliente', primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('dni', models.IntegerField(db_column='DNI', unique=True)),
                ('direccion', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('fechanac', models.DateField(db_column='fechaNac')),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('iddepartamento', models.IntegerField(db_column='idDepartamento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('iddetalleventa', models.BigIntegerField(db_column='idDetalleVenta', primary_key=True, serialize=False)),
                ('cantidad', models.SmallIntegerField()),
                ('descuento', models.FloatField()),
            ],
            options={
                'db_table': 'detalleVenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('iddoctor', models.IntegerField(db_column='idDoctor', primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('dni', models.IntegerField(db_column='DNI', unique=True)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idfactura', models.BigIntegerField(db_column='idFactura', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=1)),
                ('cuit', models.CharField(db_column='CUIT', max_length=20)),
                ('total', models.IntegerField()),
                ('fechaapertura', models.DateField(db_column='fechaApertura')),
                ('fechacierre', models.DateField(db_column='fechaCierre')),
                ('direccionenvio', models.CharField(db_column='direccionEnvio', max_length=40)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.IntegerField(db_column='idProducto', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('preciocosto', models.IntegerField(db_column='precioCosto')),
                ('precio', models.IntegerField()),
                ('fechaingreso', models.DateField(db_column='fechaIngreso')),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idprovincia', models.IntegerField(db_column='idProvincia', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idservicio', models.IntegerField(db_column='idServicio', primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('idproducto', models.IntegerField(db_column='idProducto', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idtipoproducto', models.SmallIntegerField(db_column='idTipoProducto', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tipoProducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('tipousuario', models.SmallIntegerField(db_column='tipoUsuario')),
                ('usuario', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('aceptatc', models.IntegerField(db_column='aceptaTC')),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('idvendedor', models.IntegerField(db_column='idVendedor', primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('dni', models.IntegerField(db_column='DNI', unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'vendedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.BigIntegerField(db_column='idVenta', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
