# Generated by Django 4.2 on 2023-05-25 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abono',
            options={'managed': False, 'verbose_name_plural': 'Abonos'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'managed': False, 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'managed': False, 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'managed': False, 'verbose_name_plural': 'Detalle Ventas'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': False, 'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'managed': False, 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False, 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'managed': False, 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'managed': False, 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'managed': False, 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterModelOptions(
            name='tipoproducto',
            options={'managed': False, 'verbose_name_plural': 'Tipos Producto'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False, 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'managed': False, 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'managed': False, 'verbose_name_plural': 'Ventas'},
        ),
    ]
